### ISSUE TITLE
Allow Date object as a parameter/ result

### ISSUE THREAD

**Issue by gajus** [gajus/slonik#113]
It has been [proposed](https://github.com/gajus/slonik/issues/94) that date types that describe timestamp should be parsed into Date object, and that when Date object is provided, it should be converted into a timestamp that PostgreSQL understands.

In general, I am opposed to using Date object at all, because of the mutable API. However, with regards to reading values from the database, I can see some value in returning `Date` as it provides a uniform data type for arbitrary accuracy timestamp values (in contrast, Slonik assumes millisecond accuracy).

With regards to accepting Date object as a parameter, would it require to simply translate Date to string  and use that as a value?

**Comment by gajus** [comment]
cc @ivan-kleshnin @camflan

**Comment by camflan** [comment]
If we're passing a `Date` instance to slonik, shouldn't we simply use `date.getTime()` to get the ms timestamp?

Re your concerns around mutability, I agree. I don't use Date directly, but instead via date-fns (and similar home grown fns) to avoid mutating the original Date. What are you using to deal with dates in an immutable fashion?

**Comment by gajus** [comment]
> If we're passing a Date instance to slonik, shouldn't we simply use date.getTime() to get the ms timestamp?

Timestamp can be more accurate than milliseconds, though.

> What are you using to deal with dates in an immutable fashion?

date-fns

**Comment by camflan** [comment]
> Timestamp can be more accurate than milliseconds, though.

Right, but if we're given a Date, then isn't ms is the most precise info we have?

> > What are you using to deal with dates in an immutable fashion?
> 
> date-fns

Cool - we're on the same page. 👍

**Comment by gajus** [comment]
> Right, but if we're given a Date, then isn't ms is the most precise info we have?

Good point.

I am honestly not sure what is the best way to proceed.

If we were to return Date, and timestamp contains microseconds, then such implementation would truncate the data.

It might be reasonable compromise to make given that use of microseconds is pretty rare.

**Comment by sgoll** [comment]
For reference, `node-postgres` itself converts date/time columns into `Date` objects and does the correct conversion when passed `Date` objects to forward them to the database:

https://node-postgres.com/features/types#date%20/%20timestamp%20/%20timestamptz

> Although PostgreSQL supports microseconds in dates, JavaScript only supports dates to the millisecond precision. Keep this in mind when you send dates to and from PostgreSQL from node: your milliseconds will be truncated when converting to a JavaScript date object even if they exist in the database. If you need to preserve them, I recommend using a custom type parser.

So there is some precedent for using `Date` objects in the Node.js world when talking to Postgres, even with the microsecond precision loss.

This said, I am in favor of following the same path and using `Date` objects when handling date/time columns. The alternatives seem either clumsy or ambiguous: ISO date strings, seconds since the epoch, milliseconds since the epoch.

For the time being, is there a workaround for handling dates/times with the default `typeParsers` disabled, i.e. passing values directly to `node-postgres`? It seems that `node-postgres` should handle `Date` just fine, but `slonik` prohibits me from sending `Date` instances downstream by throwing an error: `Must be a primitive value expression.`

**Comment by camflan** [comment]
I haven't touched this code in a while, but I remember setting `typeParsers: []` giving me the expected `Date` conversions. 

I think removing the timestamp typeParsers from the default config might give people the functionality they expect, with an ability to opt back in if they want timestamps.

**Comment by sgoll** [comment]
> I haven't touched this code in a while, but I remember setting `typeParsers: []` giving me the expected `Date` conversions.

That is correct, the only problem is that `slonik` disallows `Date` from being used as value in `sql` tokens.

`createSqlTag()` checks each value's type and generates template placeholders for everything that is considered a primitive value: https://github.com/gajus/slonik/blob/master/src/factories/createSqlTag.js#L70

`isPrimitiveValueExpression()` does not allow `Date` objects, even though `node-postgres` would be able to handle them: https://github.com/gajus/slonik/blob/master/src/utilities/isPrimitiveValueExpression.js

**Comment by gajus** [comment]
> With regards to accepting Date object as a parameter, would it require to simply translate Date to string and use that as a value?
> [..]
> isPrimitiveValueExpression() does not allow Date objects, even though node-postgres would be able to handle them: https://github.com/gajus/slonik/blob/master/src/utilities/isPrimitiveValueExpression.js

I wouldn't extend the definition to include `Date` object. I think it is really important to only bind values that are non-mutable and that can be observed at any point in the exact form as they will be sent to the database. For input, I would consider adding `sql.date()` utility, that would convert input to timestamp in milliseconds and wrap the value binding with `to_timestamp`.

This however means that `Date` would still be unusable in a lot of the cases, e.g. `unnest`.

The question is really whether the query should return `Date` object or just time in milliseconds.

**Comment by sgoll** [comment]
> I wouldn't extend the definition to include `Date` object. I think it is really important to only bind values that are non-mutable and that can be observed at any point in the exact form as they will be sent to the database.

Why is that? I was under the impression that "primitive value" in this case would simply mean that the value could be processed by `node-postgres` directly, regardless of mutability issues (which should also be the focus of the remaining application architecture but extends farther than the database access layer, I think).

As long as there are no specific security concerns (sending down unescaped values and such), I would prefer the ability to pass compatible values to `node-postgres` unmodified. The `sql` tag helper should preferably not restrict the available value set more than necessary, IMHO.

If necessary (and for clarification in case of ambiguities), I'd suggest introducing a `sql.value()` utility that explicitly forwards the wrapped value to the `node-postgres` query value array.

> For input, I would consider adding `sql.date()` utility, that would convert input to timestamp in milliseconds and wrap the value binding with `to_timestamp`.

I think you need seconds instead of milliseconds for `to_timestamp()` to work correctly.

This, BTW, is the most important concern that I have with not using `Date` objects: to me, it is often unclear what the alternative value (`string` or `number`) means: strings may be the human-readable date/time representation or an ISO date string, numbers may be seconds or milliseconds since the epoch, and so on.

The meaning is not clear in most cases from just looking at the code and often differs between projects which is why I prefer `Date` objects whenever I can.

Instead of reimplementing the date/time conversion in `slonik` (which is what the `sql.date()` helper would do), `node-postgres` could do that dirty work by simply receiving a `Date` object.

> This however means that `Date` would still be unusable in a lot of the cases, e.g. `unnest`.

I guess this would not be an issue when `Date` instances could be considered "primitive values" in the sense of "pass them to the underlying database layer and let that handle them".

`node-postgres` is able to handle arrays of `Date` objects, so passing those into the `unnest()` function would not be a problem.

> The question is really whether the query should return `Date` object or just time in milliseconds. Among other concerns, it is less memory efficient, requires casting to integer when the intent is to get milliseconds, and broadens the static type definition of the result row.

I guess I have no preference here. Since custom `typeParsers` can handle any necessary conversion, it is up to the user to configure exactly what they want. When no type parsers are installed at all, the value would be forwarded from `node-postgres`. If users are not happy with that value or type, a custom type parser can convert the result in either (milli-)seconds since the epoch or some custom date-like object.

**Comment by gajus** [comment]
> I was under the impression that "primitive value" in this case would simply mean that the value could be processed by node-postgres directly, regardless of mutability issues [..]

Primitive value literally refers to JavaScript primitives (boolean, number, string, null).

> I think you need seconds instead of milliseconds for to_timestamp() to work correctly.

This is incorrect.

> This, BTW, is the most important concern that I have with not using Date objects: to me, it is often unclear what the alternative value (string or number) means: strings may be the human-readable date/time representation or an ISO date string, numbers may be seconds or milliseconds since the epoch, and so on.

This is true about any data you retrieve from the database. Using Slonik at the moment, you can be sure that the timestamp data you receive from the database is time in milliseconds.

**Comment by rtbo** [comment]
>  I think you need seconds instead of milliseconds for to_timestamp() to work correctly.
> > This is incorrect.

According PSQL docs, `to_timestamp` takes seconds since epoch as parameter, but can be supplied double precision.

I don't really mind entering/getting `Date` or milliseconds. The `Date` API makes both very accessible.
As `Date` is less efficient and trivially constructible from milliseconds, milliseconds should be preferred as in/out timestamp interface.
Input helpers and optional type parsers should be proposed as suggested.

As for what `node-postgres` is doing, it converts the date object to a string before giving it to postgresql. And the server needs to do the same processing backwards to store it as microseconds.

Without mentioning the mutability concern, this is far from optimal, and a `sql.timestamp` that wraps milliseconds in `to_timestamp` would be very welcome in this regard, especially if usable in `sql.unnest`.
`sql.date` would trivially call `sql.timestamp`.

**Comment by adevine** [comment]
First, just wanted to say thanks so very much for this library. I just discovered this today and this is exactly what I've been looking for in a SQL library for a long time. I greatly appreciate all of your work!

On to my question, I'm just curious as to what most folks are doing _now_ when it comes to querying timestamp columns. I have this simple function (in typescript) so I can pass Dates as Timestamps:

```
// To be honest I haven't fully grokked the TypeScript typings yet
// so that QueryResultRowType<string> may not be correct
const dateParam = (dateObj: Date): SqlSqlTokenType<QueryResultRowType<string>> => {
    return sql`TO_TIMESTAMP(${dateObj.getTime()} / 1000.0)`;
};

// then in a query
const query = sql`SELECT * FROM my_table WHERE created_at > ${dateParam(someDateValue}`;
```

Agree with the comments above, would be great if this was supported by default, just curious as to how other folks are handling this now.

**Comment by darkbasic** [comment]
> As long as there are no specific security concerns (sending down unescaped values and such), I would prefer the ability to pass compatible values to node-postgres unmodified. The sql tag helper should preferably not restrict the available value set more than necessary, IMHO.

I agree, I think Slonik should handle native Date objects.

**Comment by rabidaudio** [comment]
I follow the reasoning behind the decision not to use Date, but I suggest we at least put a section in the docs. It took me a while to figure out the `to_timestamp(${date.getTime()} / 1000)` solution, and it seems the millisecond conversion is an opportunity for bugs.

**Comment by darkbasic** [comment]
Using `raw` with `Date` works as well.

**Comment by charlex** [comment]
Just dropping this here for those who come here late at night, forgetful that if the time you are trying to input is now, just do:

```
const query = sql`SELECT * FROM my_table WHERE created_at > now()`;
```

I was on this thread, and was going to implement @adevine 's solution, but then I remember what I was doing was simple :)

**Comment by draconteus** [comment]
Is there any decision in this issue? It's really frustrating to figure out how to handle dates :( JSON has out of the box solution for immutability.

**Comment by gajus** [comment]
Part of the problem is that there is no consistency in the Node.js ecosystem as to how dates are passed around.

https://twitter.com/erikras/status/1374069084099317765

There is an even split between people just passing around UNIX timestamp as an integer and `Date` object.

Earlier it was proposed to add `sql.date`. Implementation would roughly look as follows:

```js
const date = (input: Date) => {
  return sql`to_timestamp(${input.getTime() / 1000})`;
};

```

The value of this seems very minimal, esp. considering that it would not work with unnest.

Meanwhile, anyone who wish to get `Date` object from SQL results, you can configure `typeParsers: []`.

In order for this to proceed further, I would need someone to come up with a proposal and summarize pros and cons. Otherwise, there is no action here.

**Comment by escobar5** [comment]
Could we at least update the docs to show how to insert a Date? I could make a PR, but I don't even know what is the recommended way to insert a date into a slonik query.

**Comment by hexcowboy** [comment]
Postgres accepts ISO date strings, so really this isn't as complicated as everyone in this thread is making it out to be.

Here's an example:
```ts
// Select users updated within the last 10 minutes
const now = new Date(Date.now() - 1000 * 60 * 10); // 10 minutes ago
await client.query(sql`SELECT user WHERE updated_at > ${now.toISOString()}`);
```

There is also nothing wrong with passing milliseconds although I'm a strong believer of not using Postgres functions when your application can handle the logic.

**Comment by gajus** [comment]
PR for review https://github.com/gajus/slonik/pull/383
