### ISSUE TITLE
Instantiate slonik using an existing pg connection

### ISSUE THREAD

**Issue by jgoux** [gajus/slonik#126]
Hello,

I'm using [postgraphile](https://www.graphile.org/postgraphile/) to build my GraphQL API.

Postgraphile manages its own transactional context using `pg`.

In order to be able to use other postgres clients than the one provided by postgraphile, these clients have to be instantiable with an existing `pg`'s connection (so we can use the same transaction handled by postgraphile).

So far it's not possible to do it with slonik (neither with pg-promise).

I think it would be a great addition.

**Comment by gajus** [comment]
In this scenario, what is the value of using Slonik?

Is it all the convenience methods like 'one`, `anyFirst`, etc.?

**Comment by jgoux** [comment]
Yes and the type safety too. I won't lie that I also have an eye on photonjs. 👀

**Comment by gajus** [comment]
I like this requirement primarily because it has a potential of adding a layer of abstraction that enables cross-driver compatibility.

I would imagine that this could work by adding `useConnection` function that would be responsible for making the actual query, e.g.

```js
const connection = useConnection(
	async (sql, values) => {
		const result = await yourConnection.query(sql, values);

		// Your responsibility to format results in a way that is compatible with Slonik.
		return result;
	});


```

The challenge though is that really complicates how methods like `stream` are implemented.

**Comment by darkbasic** [comment]
In my project I use [Mikro-ORM](https://mikro-orm.io/) but I need to hand-write a couple of very complex queries.
Mikro-ORM uses Knex.js under the hood and allows you to [retrieve a knex instance](https://mikro-orm.io/docs/query-builder#using-knexjs).
I cannot use Knex.js because there are just too many partitions/case statements/lateral joins and other advanced features which are not supported.
Also I prefer to write plain queries and since I also need dynamic conditions, syntax highlighting and automatic parameters binding slonik looks like a good candidate.
The problem is that AFAIK knex doesn't allow me to consume queries with pg-like bindings (`$1 $2`), so accessing the knex instance is not useful.
There is also an [execute method](https://mikro-orm.io/docs/query-builder#running-native-sql-query) in Mikro-ORM, but I think it still uses Knex.js under the hood because the parameter binding is done through `?` instead of `$1`.
Is there any way to use slonik through any existing db connection?

**Comment by gajus** [comment]
> Is there any way to use slonik through any existing db connection?

There is not. Just start a new connection. What's the problem?

**Comment by gajus** [comment]
Not planning to support such use case. It would open too many edge cases.
