### ISSUE TITLE
unrecognized configuration parameter "idle_in_transaction_session_timeout"

### ISSUE THREAD

**Issue by xiaoyu-tamu** [gajus/slonik#145]
After updating to latest version, I got ConnectionError: unrecognized configuration parameter "idle_in_transaction_session_timeout".  I'm using pg version 9.5, but the  idle_in_transaction_session_timeout parameter was introduced in version 9.6.

Is there anyway to remove this parameter?

I tried to set connectionTimeout=DISABLE_TIMEOUT but it does not work.

## Expected Behavior

It can connect to postgresql below 9.6 

## Current Behavior

It cannot connect to postgresql below 9.6 

## Steps to Reproduce

1.
2.
3.
4.

## Logs

<-- Capture and include logs https://github.com/gajus/slonik#logging -->

**Comment by gajus** [comment]
The configuration is `idleInTransactionSessionTimeout=DISABLE_TIMEOUT`.

**Comment by richmolj** [comment]
I'm not sure that addresses the issue (which I am also having). Regardless of how you set this option in Slonik, the issue is the underlying config is not supported in PG 9.5 (see [here](https://github.com/gajus/slonik/commit/9e98a39e034679d8892c6b3897fa4d8eda96caa5#diff-49914035aae1ebbfce67fe23903ebc26R39)).
