### ISSUE TITLE
Question : typing one/oneFirst

### ISSUE THREAD

**Issue by dmpvost** [gajus/slonik#148]
How we should type for using one : 

```js
let result: Obj = await Pg.connection.one<Obj>(sql`QUERY`)

```

And oneFirst? What is <T[keyof T] ?

No idea how to type it

```js
let result: Obj = await Pg.connection.oneFirst<Obj>(sql`QUERY`)

```

Often, I return a object in JSON from database, so I use often oneFirst to get first colonne, first field

**Comment by gajus** [comment]
TypeScript question is unlikely to get answered here.

Your best bet is to ask in https://github.com/DefinitelyTyped/DefinitelyTyped/ and mention people who contribute to the Slonik types.

Generally, since the query response is dynamic, types for it should be taken as a guide, rather than a rule. In case of Flow, if I was to return a boolean from a `oneFirst` and I wanted my value to have that type association, I would just do:

```js
// $FlowFixMe
const result: boolean = await pool.oneFirst(sql`SELECT [..]`);

// or
// const result: boolean = (await pool.oneFirst(sql`SELECT [..]`): any);

```

**Comment by dmpvost** [comment]
ok thank ;)
