### ISSUE TITLE
Serializable transactions not working as intended

### ISSUE THREAD

**Issue by derekchiang** [gajus/slonik#163]
I've created a repo that reproduces this issue: https://github.com/derekchiang/postgres-bug

Basically, I'm running some code in a serializable transaction like this (pseudocode):

```
BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE

const userCount = select count(*) from missions
if (userCount == 0) {
  insert into users default values
}

COMMIT
```

Now, when you run this transaction many times in parallel, you'd think that only one row would be created.  However, as you can see from the test in the repo, more than 1 rows wound up getting created.

It's not clear to me whether this is a bug in Slonik or Postgres, or if I'm fundamentally misunderstanding something.  But I thought I'd put it here in case it's an issue in Slonik.

**Comment by gajus** [comment]
Sounds like a question for Stack Overflow.

**Comment by derekchiang** [comment]
Are you sure this is not an issue in Slonik?

**Comment by derekchiang** [comment]
@gajus I confirmed that this issue only happens with `slonik` but not with `pg`.

Here's the code for `pg`: https://github.com/derekchiang/postgres-bug

Here's the code for `slonik`: https://github.com/derekchiang/postgres-bug/tree/slonik

`pg` passes the test but `slonik` doesn't.   Please take a look, I really think there's an issue with serializable transactions with slonik.

**Comment by TriStarGod** [comment]
@derekchiang Could it be that the transaction isolation reverts in slonik after the promise executes since you're running the code within another transaction? Even if its considered an async function, its still running on a single thread due to NodeJs. Try running the transaction isolation, selects and inserts in pool.connect / query instead of pool.transaction

**Comment by gajus** [comment]
Please see below to understand how transactions are implemented:

* https://github.com/gajus/slonik/blob/master/src/connectionMethods/transaction.js
* https://github.com/gajus/slonik/blob/master/src/connectionMethods/nestedTransaction.js

**Comment by nponiros** [comment]
I also had issues with my serializable transactions and after lots of searching and trying I set the `transactionRetryLimit` option to 0 and everything seems to work as expected. I had a quick look at the code but I don't understand how transaction retrying really works. From the option's description I guess it only executes the SQL part of the transaction but not what is done in JavaScript which is what in my case causes serializable transactions to fail. Maybe this can be added as an info to the readme file to save the next person some time.

**Comment by casey-chow** [comment]
> From the option's description I guess it only executes the SQL part of the transaction but not what is done in JavaScript which is what in my case causes serializable transactions to fail.

That lines up with my reading of the code as well:

https://github.com/gajus/slonik/blob/72f97820f9fe5f83a8820029d8ead64189f48360/src/routines/executeQuery.ts#L75-L96

So this retry mechanism doesn't retry by rerunning the code in the transaction function, it retries by _replaying_ the generated queries captured during the course of the function run. Since the transaction retry doesn't validate that the select queries return the same value as before, it's fairly clear that the auto-retry mechanism is poorly suited for read-modify-write operations. Implementing a retry by re-calling the entire function, of course, comes with its own drawbacks, but it does seem like most people (myself included) expect that kind of implementation when told that slonik supports auto-retrying.

**Comment by nponiros** [comment]
From what I can tell the way to fix this is to:

1. remove the retry mechanism for transactions from https://github.com/gajus/slonik/blob/master/src/routines/executeQuery.ts. (Retry in that file should probably be changed to support implicit pool queries for #176)
2. Add a retry mechanism based on the handler function in https://github.com/gajus/slonik/blob/master/src/connectionMethods/transaction.ts and https://github.com/gajus/slonik/blob/master/src/connectionMethods/nestedTransaction.ts
3. Optional: add a transactionRetryLimit parameter to the transaction method so that we can define which transactions  should be retried and which not. If the parameter is undefined the global parameter should be used

I don't see any major drawbacks of calling the handler function of the transaction. Using global state in the handler function could cause issues but I don't think that those are worse than what is happening now.

@gajus are the changes that I proposed something that you are willing to merge if I open a PR for it or do you see any issues that I don't?

**Comment by mgreenw** [comment]
Thanks @nponiros and @gajus!
