### ISSUE TITLE
How to select an array of tuples (multiple columns) `WHERE (column1, column2) = ANY` with Slonik?

### ISSUE THREAD

**Issue by attilaaf** [gajus/slonik#192]
How to select an array of tuples (multiple columns) `WHERE (column1, column2) = ANY` with Slonik?

## Expected Behavior

Given an array of tuples, I wish to select all rows matching both columns.

Example desired dynamic query:

```
SELECT * FROM orders WHERE (orderid, name) = ANY (('order123', 'bob'), ('order453', 'alice'))
```

Where we have the array of tuples to use to query on columns `orderid` and `name`

`let orderLookup = [ { orderid: 'order123', name: 'bob' } ,  { orderid: 'order453', name: 'alice' }]`;
 
## Current Behavior

The documentation does not show how to use WHERE IN or WHERE = ANY with multiple columns.

## Possible Solution

I tried using `sql.array` but could not figure out how to bind the rows of tuples.

## Steps to Reproduce

Unknown.

## Logs

N/a

**Comment by gajus** [comment]
You can do:

```js
const g = (members) => {
  return sql`(${sql.join(members, sql`,`)})`;
};

${g([sql.identifier(['orderid']), sql.identifier(['name'])])} = ANY ${g([
  g(['order123', 'bob']),
  g(['order123', 'bob']),
])}

```

However, if I was to do the same, I would do it as:

```js
$({sql.join(orderLookup.map(ol => sql`orderid ${ol. orderid}  = AND name = ${ol.name}`), sql`) OR (`)});
```

**Comment by alitaheri** [comment]
I just stumbled upon this. And after doing some research I came to another conclusion:

```ts
const myList = [['order123', 'bob'], ['order453', 'alice']];

const filtered = await connection.any(sql`
  SELECT orderid, name
  FROM orders, ${sql.unnest(myList, ['text', 'text'])} AS my_list(orderid, name)
  WHERE (orderid, name) IN (my_list)
`)
```

I have tested this approach and it seems to be working fine with my data. I checked the plan and it looks fine to me, not much different from other approaches. Doesn't even prevent an index-only scan. What's great about this approach is that it will keep the query constant size. 

So @gajus  my question is, do you think this approach should be the de-facto? I mean, you have said many times in your blogs and on the documentation that using `sql.unnest` or `sql.array` is recommended because of the reasons we all know. So, if you think this is a good approach, I would like to make a pull request and add this to the documentation. It took me 3-4 hours of research and experimentation to come up with this solution, adding it to the docs will definitely help a lot of people.
