### ISSUE TITLE
Connection and transactions handling

### ISSUE THREAD

**Issue by Ericnr** [gajus/slonik#206]
I appreciate the concern for safety when managing connection and transactions, but in cases safety is not as important (automated tests) it'd be useful to be able to pass around connections and transactions. Even if the api is `const connection = await pool.UNSAFE_connect()` it'd make things easier in some cases.

**Comment by gajus** [comment]
Just create your own methods.

```sql
const startTransaction = (connection) => connection.query(sql`BEGIN`);
```

**Comment by Ericnr** [comment]
sure, that works with transactions, but how do I "BEGIN" a connection?

**Comment by gajus** [comment]
Something like this would work:

```js
const connect = () => {
  let resolveConnection;

  const connectionPromise = new Promise((resolve) => {
    resolveConnection = resolve;
  });

  pool.connect((connection) => {
    return new Promise((resolve) => {
      connection.end = resolve;

      resolveConnection(connection);
    });
  });

  return connectionPromise;
};

```

**Comment by AndrewJo** [comment]
For those that stumbled upon this issue with the need to use transactions in tests, I wrote a library called [mocha-slonik](https://github.com/AndrewJo/mocha-slonik) that automatically wraps all Slonik's query APIs in transactions that automatically rolls back after each tests. 

This is probably truer to the spirit of Slonik's philosophy where we want transactions managed automatically instead of manually managing it.
