### ISSUE TITLE
Clarification on explicit vs. implicit queries

### ISSUE THREAD

**Issue by jdhanoj-jci** [gajus/slonik#249]
Hello!

We are using slonik for a fairly large project and have some questions on using implicit queries (`connection.query` without using `pool.connect` first). Until now, we have been using explicit queries by utilizing `pool.connect` before making any queries. 

After doing some performance/load testing, we have found that we get a substantial performance benefit by forgoing `pool.connect` in favor of the implicit calls. This is expected after reading through the source code and previous issues since we are now able to utilize 'idle' clients instead of always going through the overhead of establishing a new connection.

The questions then are:

1.  The documentation seems to nudge users (or at least our reading of it) toward using `pool.connect` for all requests. We are sure there is a good reason for this - could we get some clarification as to why we would want to create a new connection every time we make a call and not utilize idle clients? 
2. Is there any potential downside for us to switch entirely to implicit queries for SELECTs & INSERTs? This is desirable given the performance benefits we see, just unsure if we are missing something obvious that will bite us.

Thanks a bunch for developing this library, it has been a joy to work with!

**Comment by gajus** [comment]
The answer depends on what you are building.

For an API / web service, it makes a lot more sense to use connection pool + transactions.

For services that are running in the background (e.g. ETL), it makes more sense to use dedicated connections because you are likely going to need to set variables that last for the duration of the connection (timeouts, memory limits, etc).

There is no downside to implicit connections otherwise.
