### ISSUE TITLE
Spread Syntax causes Maximum Call Stack Exceeded exception

### ISSUE THREAD

**Issue by abraithwaite** [gajus/slonik#344]
We're seeing this in our app for very large insert statements:

```
RangeError: Koa uncaught error: Maximum call stack size exceeded
    at sql (/home/deploy/node_modules/slonik/src/factories/createSqlTag.ts:81:23)
    at buildInsertClauses (/home/deploy/src/db-lib/store/slonik/query.ts:170:27)
```

Corresponding with this line in the master branch:

https://github.com/gajus/slonik/blob/master/src/factories/createSqlTag.ts#L83

An example of my understanding of how these differ (although you probably know better than me, I'm new to TS):

https://stackoverflow.com/questions/48865710/spread-operator-vs-array-concat

## Expected Behavior

Shouldn't throw for large inserts.

## Current Behavior

Throws the above exception.

## Possible Solution

Could possibly use concat over `push` with spread syntax.

## Steps to Reproduce

1. Create a sql.join statement with a very large number of rows (100s of thousands)

**Comment by trygveaa** [comment]
I ran into this as well now. It happens for me when I try to run an insert query with more than around 125000 parameters. I got this many parameters because each row had 6 parameters, and I tried to insert 25000 rows.

Maybe it's not feasible to have that many parameters, but it would be nice with a more obvious error message.

**Comment by gajus** [comment]
Need to see an example of an actual query.

Could be many different things.

**Comment by sadiqkhoja** [comment]
Here is an example query, it fails with `Maximum call stack size exceeded` if `objs` variable contains 25000 objects 
```
const q = sql`
insert into table1 (column1, column2, column3, column4, column5, column6, column7, column8)
values ${sql.join(
    objs.map((obj) => sql`(${sql.join(obj, sql`,`)})`),
    sql`,`
  )}`;
```

is there a recursive call here?

**Comment by sadiqkhoja** [comment]
I changed the following line in `createSqlTag`
```
parameterValues.push(...sqlFragment.values);
```
to 
```
for(const v of sqlFragment.values){
    parameterValues.push(v);
}
```

That resolved the `Maximum call stack size exceeded` exception but postgresql started throwing `08P01 bind message has N parameter formats but 0 parameters` error because postrgresql can only accept 65535 parameters. As mentioned [here](https://github.com/gajus/slonik#user-content-slonik-recipes-inserting-large-number-of-rows) right way to bulk insert is to use `sql.unnest` instead of `sql.join`. I think this issue can be closed.

**Comment by gajus** [comment]
https://github.com/gajus/slonik/commit/92ccf85499241272180f94ad84c2e03554bdbd8d
