### ISSUE TITLE
Allow $\d+ as a literal value

### ISSUE THREAD

**Issue by gajus** [gajus/slonik#40]
```sql
SELECT '$1'

```

**Comment by gajus** [comment]
There isn't an easy fix without implementing an entire SQL parser, e.g. ``'foo $1 bar'` would be impossible/ hard to handle predictably, questions like quote escaping come to mind. Unlikely that this issue is worth solving before someone actually comes forward with a use case.

**Comment by gajus** [comment]
One can also simply use value expression:

```js
sql`SELECT ${'$'}`

```

as suggested by @Sharaal in https://github.com/Sharaal/sql-pg#known-issues

**Comment by Sharaal** [comment]
Just FYI: I was able to entirely get rid of `$` replacement, so this problem seems to be solvable without a SQL parser.

My approach:
The `sql` tag function and all `sql.*` helper functions returns a function for the current start position number. The `sql` tag function also resolve itself with 0 for the case its directly used for `client.query` and in this case all `sql.*` helper functions gets also resolved and know the actual parameter position they will have at the end. Hopefully that was helpful and understandable.
