### ISSUE TITLE
Sql typing no longer works with interface types

### ISSUE THREAD

**Issue by kkorenius** [gajus/slonik#410]
Trying to use an interface type with an SQL query, for example:

```
interface Person {
  id: number,
  name: string,
};

const query = sql<Person>`
  SELECT id, name
  FROM person
`;

const onePerson = await connection.one(query);
```

## Expected Behavior
The code above should compile correctly.

## Current Behavior
TypeScript compiler gives the following error:
```
TS2344: Type 'Person' does not satisfy the constraint 'QueryResultRow'.
  Index signature for type 'string' is missing in type 'Person'`.
```

The code works if the interface is replaced with a type alias.

## Possible Solution

The code was working before release 30.4.2. The problem has been probably caused due to adoption of MixedRow

**Comment by gajus** [comment]
This feature was removed in v31. I think 30.4.2 was flopped release.

Can you give 30.4.3 a try?

**Comment by gajus** [comment]
Released v30.4.4 to npm

**Comment by gilamran** [comment]
@gajus This is still an issue, it's impossilbe to work with interfaces and `sql`
I tried all these versions: `30.4.2` `30.4.4` and the latest `31.2.4`
All show the same error:
<img width="478" alt="image" src="https://user-images.githubusercontent.com/1621965/193356758-183b0086-3fd9-484f-941c-5a9c4ab71361.png">

**Comment by gajus** [comment]
Assuming this worked before, downgrading further will eventually find a version that works. It should be v30.4.4 though.

However, given that these are no longer supported, their use is highly discouraged.

**Comment by gilamran** [comment]
@gajus what isn't supported? interfaces?

**Comment by gajus** [comment]
Interface support has been removed. All static types are getting removed in favor of Zod in future versions.

https://github.com/gajus/slonik#runtime-validation

**Comment by gilamran** [comment]
That's BIG... maybe too big

**Comment by gajus** [comment]
See long discussion in this thread

https://github.com/gajus/slonik/issues/364

and this article

https://contra.com/p/gkOQlbLq-validating-postgre-sql-query-results-using-runtime-checks

**Comment by mmkal** [comment]
@gajus I'm a bit surprised that thread is the reference point for how this dramatic decision was made. That thread, in my opinion, establishes that it would have been a bad design decision to remove plain interface support since it's completely unnecessary for the zod feature. Then interface support was just removed as a follow up, without any external review or further opportunity for comment by me or others who have contributed to slonik over the years, as far as I could tell.

@gilamran I am on the lookout for a more suitable library for my team and will likely not maintain `@slonik/migrator` or `@slonik/typegen` once we have stopped using slonik. There are a few contenders, so happy to chat about it if you're thinking along the same lines. I'm on discord with the same username.

**Comment by gilamran** [comment]
@mmkal I totally with you on this. Removing support for interfaces on some minor version is not acceptable in my opinion. 
Moving this library to a runtime validation (without any option to opts out) is not what I am looking for.
I've also started looking for alternatives, not doing so will get me stuck on version 30.4.4 forever.

p.s. I don't see your comment as rude. Any contributor's opinion should be heard. This is open source.
