### ISSUE TITLE
How to use WHERE id IN

### ISSUE THREAD

**Issue by premsgr** [gajus/slonik#430]
I want my query generated like this but it adds extra double quotes infront of the values and turns like this 

Expected  behaviour
SELECT *
      FROM posts
      WHERE id IN ('500a2396-ff29-490e-beb8-ef250ada8027', '90ea66c1-069e-4418-bb45-95b83b8b8ece')

Result
{
  sql: 'SELECT * \n        FROM posts \n        id IN ($1) \n      ',
  type: 'SLONIK_TOKEN_SQL',
  values: [
    "'500a2396-ff29-490e-beb8-ef250ada8027', '90ea66c1-069e-4418-bb45-95b83b8b8ece'"
  ]
}

The values has extra "

**Comment by aust1nz** [comment]
I don't think this is a Slonik bug. Here's a similar query I have:

```
const query = sql.type(databaseModel)`
    SELECT *
      FROM "databaseModel"
     WHERE "id" IN ('12345')
  `;
```

And here's what Slonik converts that sql to:
```
sql: '\n' +
  '    SELECT *\n' +
  '      FROM "schoolLeaderReviews"\n' +
  `     WHERE "employeeID" IN ('12345')\n` +
  '  ',
```

In real code the ids in IN are going to be dynamic, though. In those cases, my examples look more like the following:
```
const query = sql.type(databaseModel)`
    SELECT *
      FROM "databaseModel"
     WHERE "id" IN (${sql.join(ids, sql`, `)})
  `;
```

Which is converted to the following:

```
sql: '\n' +
  '    SELECT *\n' +
  '      FROM "schoolLeaderReviews"\n' +
  '     WHERE "employeeID" IN ($1, $2, $3, $4, $5)\n' +
  '  ',
type: 'SLONIK_TOKEN_SQL',
values: [
  '12345', '12346', '12347', '12348',
  '12349'
]

**Comment by AndrewJo** [comment]
The hint to the problem is with the prepared statement output you provided: `SELECT * \n FROM posts \n id IN ($1) \n`.

If you copy this prepared statement and bind the values directly in the `node-postgres` driver and run it (bypassing Slonik altogether), you'll notice that the driver will do the same thing. This is because at the driver level, the `$1` argument in your prepared statement means that it's a single location to bind the value. Passing the array in there will just tell the driver, "bind a single value into this placeholder" where the value is a JavaScript array object. The driver tries to be clever and converts the array object into a string: `"'500a2396-ff29-490e-beb8-ef250ada8027', '90ea66c1-069e-4418-bb45-95b83b8b8ece'"`.

Note that the prepared statement that @aust1nz generated has distinct parameters in the WHERE IN statement: `WHERE "employeeID" IN ($1, $2, $3, $4, $5)`. This means that 5 distinct values can be bound inside the parenthesis which is why his statement works. 

However, be careful with this method if you have a potential for a large array (especially if this array can be user generated via form data, query params, etc.). In PG wire protocol, the `number-of-parameters` field in bind messages is int16 which effectively limits the number of parameters to 32767 (meaning after parameter `$32767`, there is little that driver could do to bind additional values).

If you wish to bind any arbitrary sized array with a single parameter, you can do this:

```typescript
sql.type(postSchema)`SELECT * FROM posts WHERE id = ANY(${sql.array(postIds)})`
```

The above statement has identical behavior as a WHERE IN clause and doesn't have the int16 limitation. According to the [PostgreSQL manual](https://www.postgresql.org/docs/current/functions-subquery.html#FUNCTIONS-SUBQUERY-ANY-SOME), `IN` is identical to `= ANY`. In fact, PostgreSQL query optimizer will almost always convert `IN` into `= ANY` iirc (you can verify the query plan with an `EXPLAIN` query).

Bonus: if you need to do `NOT IN`, use the logical negation of `= ANY` which would be `<> ALL`.

See also: 
- [node-postgres: how to execute "WHERE col IN (<dynamic value list>)" query?](https://stackoverflow.com/questions/10720420/node-postgres-how-to-execute-where-col-in-dynamic-value-list-query) (StackOverflow).
