### ISSUE TITLE
Zod local version must be equal to slonik zod version

### ISSUE THREAD

**Issue by mvcodelabs** [gajus/slonik#449]
If the version of zod in the local package.json is greater than slonik zod version, typescript refuses to compile indicating that the internal zod types are different.

Example:
slonik - `zod: 3.19.2`
local (with yarn add) - `zod: 3.20.2`

Error:
```
// ...
Types of parameters 'input' and 'input' are incompatible.
        Type 'Zod.ParseInput' is not assignable to type 'import("**local_project**/node_modules/zod/lib/helpers/parseUtil").ParseInput'.
// ... same with different parameter names
```

## Expected Behavior
Code will compile indipendent of semver minor version, eg. `3.x.x`.

## Current Behavior
Code will not compile if versions don't match.

## Possible Solution

Maybe peer dependency? Don't really know what could fix it, sorry.

## Steps to Reproduce

1. `yarn install slonik zod` -- as of today, 15 january 2023 the default of zod is `3.20.2`
2.  `sql.type(zodObject)`

## Logs
No runtime usage

**Comment by gajus** [comment]
@colinhacks any suggestions how to best solve this?

**Comment by dilame** [comment]
> @colinhacks any suggestions how to best solve this?

I'm sorry, not sure if mr @colinhacks have something to do with it, because this is the exact case for peer dependency – it was introduced specifically for solving this type of issues. 

The solution in this case is simple – you specify `"zod": "^3.0.0"` as both `peerDependencies` and `devDependencies` (but not in `"dependencies"`). 
`peerDependencies` requires the end user to install `zod` by himself, while `devDependencies`  enables `slonik` maintainers to rely on zod typings.

**Comment by gajus** [comment]
> > @colinhacks any suggestions how to best solve this?
> 
> I'm sorry, not sure if mr @colinhacks have something to do with it, because this is the exact case for peer dependency – it was introduced specifically for solving this type of issues.
> 
> The solution in this case is simple – you specify `"zod": "^3.0.0"` as both `peerDependencies` and `devDependencies` (but not in `"dependencies"`). `peerDependencies` requires the end user to install `zod` by himself, while `devDependencies` enables `slonik` maintainers to rely on zod typings.

That will fix the particular issue at hand. And maybe that's enough. The reason for tagging Zod team though is because this could also be solved by providing a more general type to check against.

**Comment by dilame** [comment]
> That will fix the particular issue at hand. And maybe that's enough. The reason for tagging Zod team though is because this could also be solved by providing a more general type to check against.

`zod` in this case is a peer dependency by it's nature, and have it in `"dependencies"` section is incorrect regardless if zod team can provide a more general type or not (they can not though). Moreover, the issue is not even in zod versions incompatibility, but in 2 separate installations. Here is the full error message

`
TS2345: Argument of type 'ZodObject<{ asset: ZodString; amount: ZodString; }, "strip", ZodTypeAny, { asset: string; amount: string; }, { asset: string; amount: string; }>' is not assignable to parameter of type 'ZodTypeAny'.   Types of property '_parse' are incompatible.     Type '(input: ParseInput) => ParseReturnType<{ asset: string; amount: string; }>' is not assignable to type '(input: ParseInput) => ParseReturnType<any>'.       Types of parameters 'input' and 'input' are incompatible.         Type 'import("/Users/bowzee/WebstormProjects/trading.bot/node_modules/slonik/node_modules/zod/lib/helpers/parseUtil").ParseInput' is not assignable to type 'Zod.ParseInput'.           The types of 'parent.common.issues' are incompatible between these types.             Type 'import("/Users/bowzee/WebstormProjects/trading.bot/node_modules/slonik/node_modules/zod/lib/ZodError").ZodIssue[]' is not assignable to type 'Zod.ZodIssue[]'.               Type 'import("/Users/bowzee/WebstormProjects/trading.bot/node_modules/slonik/node_modules/zod/lib/ZodError").ZodIssue' is not assignable to type 'Zod.ZodIssue' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.                 Type 'ZodInvalidLiteralIssue & { fatal?: boolean; message: string; }' is not assignable to type 'ZodIssue' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.                   Type 'import("/Users/bowzee/WebstormProjects/trading.bot/node_modules/slonik/node_modules/zod/lib/ZodError").ZodInvalidLiteralIssue & { fatal?: boolean; message: string; }' is not assignable to type 'Zod.ZodInvalidLiteralIssue & { fatal?: boolean; message: string; }' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.                     Property 'received' is missing in type 'ZodInvalidLiteralIssue & { fatal?: boolean; message: string; }' but required in type 'ZodInvalidLiteralIssue'.`


In my case the issue is in tsconfig `exactOptionalPropertyTypes: true`. 

I can not tell for the zod team, but i can safely assume that the whole point of releasing new versions of libraries is the changes, so i assume it is impossible for zod team to guarantee that every new version will be 100% exactly the same as previous. That's why i think zod team has nothing to do with it.

In the same time you have two local copies of `zod` in the paths 

`node_modules/slonik/node_modules/zod`
`node_modules/zod`

Obviously, you will end up with some incompatibility. This is something that should not happen anyway. 

This would be ok if you would only use `zod` internally. But you don't. In fact, `slonik` does not work with `zod` directly, and does not really depend on `zod` directly. `slonik` only use `zod` type interfaces, but only the end user really works with and depends on `zod`. So, `slonik` should **only** rely on a userland's `zod` installation. Simply because user will not be able to use `zod` without installing it, and having another installation (`node_modules/slonik/node_modules/zod`) violates "single source of truth" principle.

**Comment by mmkal** [comment]
Here is what trpc does: https://github.com/trpc/trpc/blob/0c6ce2e7d9b3ffd677084ccd9ac0e6f912c50c70/packages/server/src/core/parser.ts#L6-L9

This is more or less what I did in  #371, too, before it was closed.

**Comment by dilame** [comment]
@mmkal yes this is also a good option.  I would prefer peer dependency, but it is definitely a matter of taste whether to manually define type interfaces or have peer dependency.

**Comment by gajus** [comment]
For now, this should be a sufficient fix https://github.com/gajus/slonik/pull/451

**Comment by dilame** [comment]
@gajus thank you for such a quick fix!
