### ISSUE TITLE
Select query does not return dates as Date instances

### ISSUE THREAD

**Issue by canastro** [gajus/slonik#456]
Having the following snippet:

```ts
const sql = createSqlTag({
	typeAliases: {
		void: z.object({}).strict(),
		id: ID
	}
});

export const Foo = z.object({
	bar: z.date()
});

const pool = await createPool(connectionString, {
	typeParsers: [...createTypeParserPreset()],
	interceptors: [
		createFieldNameTransformationInterceptor({ format: 'CAMEL_CASE' }),
		createQueryLoggingInterceptor()
	]
});

const res = await pool.one(
	sql.type(Foo)`SELECT NOW()::timestamp AS bar`
);

console.log(typeof res.bar);
console.log(Foo.safeParse(res));
```

## Expected Behavior
The expected behaviour was to have the output of `typeof res.bar` as Date and a successful safeParse over the result with Foo schema

## Current Behavior
Output of `console.log(typeof res.bar);`:

```
number
```

Output of `console.log(Foo.safeParse(res));`:

```json
{
  "success": false,
  "error": [
    {
      "code": "invalid_type",
      "expected": "date",
      "received": "number",
      "path": [
        "bar"
      ],
      "message": "Expected date, received number"
    }
  ]
}
```

## Steps to Reproduce
These are the relevant dependency versions:
```ts
		"slonik": "^33.0.3",
		"slonik-interceptor-field-name-transformation": "^1.6.5",
		"slonik-interceptor-query-logging": "^1.4.7",
		"zod": "^3.20.6"
```

Run the code snippet above.

**Comment by gajus** [comment]
It looks like you've not implemented a result parser

https://github.com/gajus/slonik#user-content-result-parser-interceptor

**Comment by samjbobb** [comment]
@gajus Wanted to fill in some more background I found related to this. 

Yes, @canastro hasn't implemented a result parser to make `sql.type(Foo)` work correctly. But I think there's another misunderstanding related to type parsers. It also caught me so I'm documenting for others.

> `console.log(Foo.safeParse(res));`
> ```
> {
>   "success": false,
>   "error": [
>     {
>       "code": "invalid_type",
>       "expected": "date",
>       "received": "number",
>       "path": [
>         "bar"
>       ],
>       "message": "Expected date, received number"
>     }
>   ]
> }
> ```

You're getting a number instead of a Date object because the [Build-in type parsers](https://github.com/gajus/slonik#built-in-type-parsers) in Slonik return a number for `timestamp` and `timestamptz`.

From that table:

> `timestamp`: Produces a unix timestamp (in milliseconds).

The relevant code is [here](https://github.com/gajus/slonik/blob/1228dba2fafcb002a7a78b76864011c08a388453/src/factories/typeParsers/createTimestampTypeParser.ts#L12). `Date.parse` returns a number not a Date object.

`node-postgres` returns Date objects by default, so this surprised me.

You can get Date objects by disabling the built-in type parsers for `timestamp` and `timestamptz`.

```js
const pool = await createPool(dbUrl, {
    // ...
    typeParsers: [
      createBigintTypeParser(),
      createDateTypeParser(),
      createIntervalTypeParser(),
      createNumericTypeParser(),
      // createTimestampTypeParser(),
      // createTimestampWithTimeZoneTypeParser(),
    ],
  });
```

Some relevant conversations here:

https://github.com/gajus/slonik/issues/57

https://github.com/gajus/slonik/issues/113

Hope that helps someone.
