### ISSUE TITLE
"Argument is not assignable" error in the Result parser interceptor example

### ISSUE THREAD

**Issue by wiktor-falek** [gajus/slonik#499]
In the  RUNTIME_VALIDATION.md there's an example on how to add a result parser interceptor, and the example has a type error.

## Current Behavior
Argument of type 'QueryResultRow' is not assignable to parameter of type 'SerializableValue'.

## Steps to Reproduce
1. Install slonik in a typescript project
2. Copy the createResultParserInterceptor declaration from  [RUNTIME_VALIDATION.md](https://github.com/gajus/slonik/blob/main/.README/RUNTIME_VALIDATION.md#result-parser-interceptor)

![image](https://github.com/gajus/slonik/assets/79018062/871d16cf-4bc1-4156-a1dd-19e4d23238a6)

**Comment by firxworx** [comment]
Agree, I have hit this too.

**Additional Error Details**

To word the issue more specifically: the `QueryResultRow` type is not compatible with `SerializableValue`.

When configuring zod parsing per the docs examples for parsing query results with zod, developers will experience a type error when creating an `Interceptor` with `transformRow()`. The `row` type of `SerializableValue` cannot be passed as an argument to the `SchemaValidationError` constructor which requires type `SerializableValue`.

The specific type error reported by TypeScript, at least on the surface, appears to be a classic array vs. non-array because it reports missing properties for `length`, `pop`, `push`, etc.

```
"Argument of type 'QueryResultRow' is not assignable to parameter of type 'SerializableValue'.
  Type 'QueryResultRow' is missing the following properties from type 'SerializableValue[]': length, pop, push, concat, and 35 more.ts(2345)"
```

**Reference**

The constructor signature for `SchemaValidationError` is: `new SchemaValidationError(query: Query, row: SerializableValue, issues: ZodIssue[]): SchemaValidationError`.

The type signature for `transformRow()` is: `((queryContext: QueryContext, query: Query, row: QueryResultRow, fields: readonly Field[]) => QueryResultRow) | undefined`

**Workaround**

@wiktor-falek I currently workaround with very hacky and un-typescript-feeling `as` casts and confirm that slonik is working fine in my projects. I absolutely try to never do the following in TypeScript code (when it can be avoided) however it gets slonik working e.g.

```ts
  return {
    transformRow: (executionContext, actualQuery, row): QueryResultRow => {
      const { log, resultParser } = executionContext

      if (!resultParser) {
        if (process.env['NODE_ENV'] !== 'production') {
          log?.debug(`query with no result parser: ${actualQuery.sql}}`)
        }

        return row
      }

      const parsedResult = resultParser.safeParse(row)

      if (!parsedResult.success) {
        log.debug({}, `slonik result parser: zod schema validation of query result failed`)
        throw new SchemaValidationError(actualQuery, row as SerializableValue, parsedResult.error.issues)
      }
      return parsedResult.data as QueryResultRow
    },
  }
```

**Conclusions**

I definitely think this should be fixed. 

@gajus I suspect a lot of developers interested in trying slonik are put off right out of the gate by this one: there's a (very warranted!) promise type safety and then in setting it up one of the first things a dev hits in terms of devX is this type error.

**Comment by firxworx** [comment]
Noting an example from another issue where this issue rears its head and complicates things for devs: https://github.com/gajus/slonik/issues/505#issuecomment-1716281517

**Comment by coreyward** [comment]
@gajus You may have closed this unintentionally—the docs still show the broken behavior where the sample code has TypeScript complaining.

**Comment by gajus** [comment]
@coreyward The changes in https://github.com/gajus/slonik/commit/40f0fd3401315445fd9415eeed9def95792cbd61 do not address the issue?

**Comment by coreyward** [comment]
@gajus Nevermind! 😅 I was looking for a documentation fix and didn't read close enough. Coffee clearly hasn't hit.
