### ISSUE TITLE
Errors lose information

### ISSUE THREAD

**Issue by mmkal** [gajus/slonik#50]
there seems to be some information lost in a `.catch` block in javascript somewhere:
setup: 
```sql
create table if not exists person(id integer primary key, name text);
```

running this in pgAdmin:
```sql
insert into person(name) values ('bob');
```
outputs:
```
ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, bob).
SQL state: 23502
```

running the same query with slonik:
```js
slonik.query(sql`insert into person(name) values ('bob');`)
```

outputs no column name, and no information about the value I tried to insert:
```
NotNullIntegrityConstraintViolationError: Query violates a not NULL integrity constraint.
```

Is there a way of having all errors include the full text that came back from the db engine?

**Comment by gajus** [comment]
Will release a fix for this that includes original error message.

**Comment by gajus** [comment]
I had a further look at this. The original reason for abstracting away this information is because the meta-data does not have a schema, i.e. there is no way to enforce type safety. This information designed to be consumed only for debugging purposes. The error is already logged in logger.

What information about the error do you wish to access and what is the intended use case?

For a lot of the cases (including `NotNullIntegrityConstraintViolationError`) we could parse the error and provide structurized meta-data.

If the intent is to simply log the error and meta attributes in external system (such as Sentry), then it would be a lot simpler to simply add `originalError` property.

**Comment by mmkal** [comment]
>What information about the error do you wish to access and what is the intended use case?

I just wanted to be able to tell what I did wrong without having to dig through code, copy-paste queries, or restart the server with `ROARR_LOG=1` (that last one isn't a bad option, but without further configuration it does produce a lot of output, so still requires plenty of digging).

The db engine error was very easy to understand and actionable - so I'd definitely be in favour of all slonik-errors having an `originalError` property. Both for humans to read, and external systems like sentry/logstash as you mention. There may even be existing postgres error parsers for some systems that could be used.
