### ISSUE TITLE
non-intuitive use template strings: "error: syntax error at or near $1"

### ISSUE THREAD

**Issue by fernandocanizo** [gajus/slonik#52]
I've been struggling for a while with this error:

```
'use strict';

const config = require('config');
const slonik = require('slonik');

const createPool = slonik.createPool;
const sql = slonik.sql;

const pool = createPool(config.pgConnectionUri);

const good = async () =>
  await pool.query(sql`
    insert into ff.users (name, password, email, fk_role) values
    ('jon doe', 'none', 'jon.doe@example.com', 'admin')`);

const bad = async () => {
  const query = `
    insert into ff.users (name, password, email, fk_role) values
    ('down jones', 'none', 'down.jones@example.com', 'admin')`;
  return await pool.query(sql`${query}`);
};

good(); // inserts ok
bad(); // error: syntax error at or near \"$1\"\n
```

I thought those two ways to make a query would be equivalent.

If I copy `console.log(query)` result and paste it on my `psql` REPL the query works fine, so it took me a good amount of time to realize `sql` template doesn't work that way.

Two questions:
1. could the error message be improved?
2. I read [Inserting large number of rows](https://github.com/gajus/slonik#inserting-large-number-of-rows) but that's awful (the $1, $2, etc. is a hard to mentally map pattern), is there a plan to include a way to pass objects to queries? Or maybe accept the bad case in may example?

My original idea was on this line:

```
const users = [ {name: '', password: '', email: '', fk_role: ''}, ...];
const userValues = () => users.map(u => `('${u.name}', '${u.password}', '${u.email}', '${u.fk_role}')`).join(',');
const query = `insert into ff.users (name, password, email, fk_role) values ${userValues()}`;
pool.query(sql`${query}`);
```

Which is a nice way to build SQL strings

**Comment by gajus** [comment]
> could the error message be improved?

Done

> I read Inserting large number of rows but that's awful (the $1, $2, etc. is a hard to mentally map pattern), is there a plan to include a way to pass objects to queries? Or maybe accept the bad case in may example?

The VALUES pattern is not recommended for inserting large number of values.

The same documentation includes an example of how to do it using `unnest`.

I am open to discuss proposals for abstractions that would make it easier to consume in a separate issue.

**Comment by vitaly-t** [comment]
> The VALUES pattern is not recommended for inserting large number of values.

Not recommended by whom, and why?

**Comment by gajus** [comment]
> Not recommended by whom, and why? People are using it everywhere these days. It is the first time I hear it being not a recommended way.

Not recommended by me.

I have documented reasons in README.md:

https://github.com/gajus/slonik#slonik-recipes-inserting-large-number-of-rows

**Comment by vitaly-t** [comment]
From your documentation there:

> The generated SQL is dynamic and will vary depending on the input.
> * You will not be able to track query stats.

This is an atomic operation, and its stats are tracked accordingly.

> * Query parsing time increases with the query size.

Only if your parser is done wrong. Otherwise, the time increase is linear, and in proportion to the number of insert values.

> * There is a maximum number of parameters that can be bound to the statement (65535).

Again, only if you are doing it wrong. If you use query templates, as one should, you will only require the number of variable to represent a single record, which makes the limit inapplicable.

---

I am not writing this to cause trouble, I have spent huge amounts of time with all this. [Here's just one post in relation to that](https://github.com/vitaly-t/pg-promise/wiki/Data-Imports). And this is how most people are using multi-row inserts.

**Comment by gajus** [comment]
> You will not be able to track query stats.
> This is an atomic operation, and its stats are tracked accordingly.

* Using my suggested approach, all query executions will be grouped together.
* Using the approach that you are advocating, there will be a separate record for every query execution with a different number of parameters.

> Query parsing time increases with the query size.
> Only if your parser is done wrong. Otherwise, the time increase is linear, and in proportion to the number of insert values.

What you said is just paraphrasing what I said: The time increase is linear, and in proportion to the number of insert values[, and that is a problem].

> There is a maximum number of parameters that can be bound to the statement (65535).
> Again, only if you are doing it wrong. If you use query templates, as one should, you will only require the number of variable to represent a single record, which makes the limit inapplicable. Also, new PostgreSQL servers removed the limit.

Can you share an actual query that you are describing?

"query template" is not a term native to PostgreSQL, therefore I am unsure what you are describing. The examples that you've linked to abstract the SQL with pg-promise API.

> I am not writing this to cause trouble, [..]

I appreciate all your input.

**Comment by vitaly-t** [comment]
I gave you a link to the the article that shows both the query and the approach - https://github.com/vitaly-t/pg-promise/wiki/Data-Imports

**Comment by gajus** [comment]
> I gave you a link to the the article that shows both the query and the approach, and performance figures - https://github.com/vitaly-t/pg-promise/wiki/Data-Imports

I've read it. As I have summarised earlier, this method is flawed for the reasons that I linked and commented on this thread. I would not recommend anyone using it. And just because _everyone_ is doing it, it doesn't make it a good way of inserting data.

I suggest that if you want to continue to have a conversation on the subject, a better medium is Freenode #postgresql channel, where PostgreSQL core developers can answer your questions/ suggest which is the best way of inserting data.

**Comment by vitaly-t** [comment]
Ok. I will stand on the opposite. Nothing you stated is wrong with the approach. And your arguments do not hold to justify changing method that's well known to work to something else, just because you think this is the way it should be.

I also gave you real-life performance figures for inserting 100m records and beyond, to which I understand have no comment, as you probably have never really tried, but you are advocating against the well-known approach nonetheless.

**Comment by gajus** [comment]
> Ok. I will stand on the opposite. Nothing you stated is wrong with the approach. And your arguments do not hold to justify changing method that's well known to work to something else, just because you think this is the way it should be.

If you would like to contribute a benchmark using this method, that would be a valuable addition to the conversation.

**Comment by flevi29** [comment]
It really doesn't help that in the official INSERT documentation there's no mention whatsoever of doing this any other way than with VALUES syntax. Do actual PostgreSQL maintainers think this is a good idea? That's what I'm curious about.

https://www.postgresql.org/docs/current/sql-insert.html

It's a little awkward to insert like this. But if it's really the way then so be it.
