### ISSUE TITLE
How to use postgres npm package with the new Driver configuration

### ISSUE THREAD

**Issue by dantio** [gajus/slonik#629]
With the refactoring in the PR [Abstract away pg](https://github.com/gajus/slonik/pull/555) it seems like the `postgres-bridge` is not working together with `postgres` npm package any more.

Would you provide the driver for `postgres` in the future? That would be great.

The main goal is to use Multi-host connections for HA. `pg` unfortunately does not support this: https://github.com/brianc/node-postgres/issues/1470

Thank you very much for your outstanding effort in maintaining this library.

**Comment by gajus** [comment]
> Would you provide the driver for postgres in the future? That would be great.

Decided against maintaining bridges within Slonik monorepo, just because I don't use them myself.

However, if someone develops one (it is just a few lines of code; can you use pg bridge as inspiration), I will happily feature it in the README.

Leaving this open to create space for discussion/updates.
