### ISSUE TITLE
Parse composite/row/record/tuple type values

### ISSUE THREAD

**Issue by noinkling** [gajus/slonik#67]
The Node Postgres ecosystem doesn't yet have an easy way to parse composite type values. `pg` and everything based on it currently just return the string representation, which isn't very useful without parsing and field type/name data. It makes a whole lot of sense for these values to be mapped to JS objects (or maybe arrays in the case of anonymous records/tuples), just as top-level result rows themselves are.

The commonly recommended workaround is to use or convert these values to JSON (via `to_json()` or similar), but JSON is very limited in the types it supports and information about the original type may be lost, removing the ability to automatically parse these types into something more suitable in JS.

The main issue with implementing this is that the wire format doesn't provide the nested field type/name information, so it requires querying the database system catalog (`pg_type`, `pg_attribute`) and all that entails. However I've noticed Slonik already does this to get the type oid from the name when registering type parsers:

https://github.com/gajus/slonik/blob/b180ebbf904be05ab230e6764bc77f22ab9a9c9b/src/routines/setupTypeParsers.js#L22

The lesser issue is that parsing the string representation for these values isn't quite as trivial as it looks at first glance, since it has to deal with nested values and a few edge cases, and the format isn't formally specified.

These issues haven't stopped various libraries in other languages supporting this functionality, which usually requires the user to manually specify which type names/oids they would like to be parsed.

With that overview out of the way, there's an issue open on the `pg` repo with more detailed information/discussion and some links which I've compiled that may be helpful: brianc/node-postgres#1801

Also, since Slonik depends on `pg` I thought you might be inclined to offer suggestions or collaborate.

**Comment by gajus** [comment]
Thanks for the detail description. I have read this + the pg issue.

I think this could be implemented as a middleware for Slonik, and I would be happy to support development by extending the middleware interface to provide the required functionality for this to be implemented.

If you are up for the task, I suggest developing it as a middleware (some examples are here https://github.com/gajus/slonik#slonik-interceptors) and then depending on what the implementation looks/ what is the overhead, this could be either added to the core or recommended as an official middleware.

I wouldn't directly develop this myself simply because I do not have a use case for it. I do recognize the JSON limitations that you've described in the `pg` issue, but I usually overcome them by casting to safe types before converting to JSON. Parsing composites would be a nice to have though.

**Comment by gajus** [comment]
This currently cannot be implemented for the reason described here https://github.com/brianc/node-postgres/issues/1801#issuecomment-533894462

**Comment by gajus** [comment]
Apepars that this is currently technically impossible to fully implement.
