### ISSUE TITLE
checking against timestamp in WHERE clause

### ISSUE THREAD

**Issue by rtbo** [gajus/slonik#70]
I must have missed something obvious.
The following code yields `TypeError: Unexpected value expression.` (triggered by the `${now}` expression)
```js
        const now = new Date();
        // ...
        await connection.query(sql`
            DELETE FROM project_member
            WHERE project_id = ${projId} AND updated_on <> ${now}
        `);
```
This is weird for me as the same `now` object was successfully used to upsert the table:
```js
    const memb = members.map(
        (m, ind) => [
            projId, m.user.id, ind, m.leader, m.designer, now,  // <---
        ],
    );
    await connection.query(sql`
        INSERT INTO project_member AS pm (
            project_id, user_id, ind, leader, designer, updated_on
        )
        SELECT * FROM ${sql.unnest(memb, ['int4', 'int4', 'int4', 'bool', 'bool', 'timestamp'])}
        ON CONFLICT(project_id, user_id) DO
            UPDATE SET
                ind = EXCLUDED.ind,
                leader = EXCLUDED.leader,
                designer = EXCLUDED.designer,
                updated_on = EXCLUDED.updated_on
            WHERE pm.project_id = EXCLUDED.project_id AND pm.user_id = EXCLUDED.user_id
    `);
```

I also tried `${now.getTime()}`, and this one yields `error: valeur du champ date/time en dehors des limites : « 1561532388000 »` (out of bound date/time field value).
This same value was stored in the database by the previous upsert.
So what is the normal way for doing this?

**Comment by gajus** [comment]
`TypeError: Unexpected value expression.` is expected because Slonik does not recognize what a `Date` object is.

The reason the example with `unnest` does not throw an error is described here https://github.com/gajus/slonik/issues/71.

As for how to insert timestamp, this is more of a general SQL question. One way to do it is:

```js
sql`
  SELECT to_timestamp({Date.now() / 1000})
`
```

In the above example, it assumes that your timestamp column type has [a precision of at least 3](https://www.postgresql.org/docs/current/datatype-datetime.html), e.g. `timestamp (3) with time zone`.

Otherwise,

```js
sql`
  SELECT to_timestamp({Math.round(Date.now() / 1000)})
`
```

We could add a helper for this of course. Just need to agree on the behaviour.
