### ISSUE TITLE
pg.Pool properties and events

### ISSUE THREAD

**Issue by ansarizafar** [gajus/slonik#92]
I am trying trying to switch from node-postgres to slonik. My current application code is using pg.Pool property pool.totalCount, connect and error events and pool.end method. Is it possible to access them from slonik?

**Comment by gajus** [comment]
What is your use case?

> pg.Pool property pool.totalCount

Your application shouldn't be aware of the connection count (beyond configuration), therefore `pool.totalCount` is not exposed.

> error events

There is no such concept as error events in Slonik (outside of stream events) because all methods are promises, i.e. you will always get promise rejection.

> pool.end method

There is no `pool.end` method because Slonik manages connection pool for you. When you are using implicit connections (i.e. `pool.query()` as opposed to `pool.connection((connection) => { return connection.query(); })`) then Pool destruction is dictated by the timeout settings. If your use case is for writing tests, then just set timeout to 0. See this thread https://github.com/gajus/slonik/issues/63
